lambdalisue/vim-fern

- autoload/fila/drawer.vim
Add variable to set drawer width
> Add g:fila#drawer#width

- autoload/fila/action.vim
Implemented toggle of tree expansion of vimfiler's function
> Add expand-toggle action

- autoload/fern/scheme/file/mapping.vim
I noticed there were some typos in the output messages
> Fix some typos

- autoload/fern/command/fern.vim
- autoload/fern/helper.vim
- autoload/fern/internal/core.vim
- autoload/fern/internal/node.vim
- autoload/fern/internal/renderer.vim
- autoload/fern/internal/viewer.vim
- autoload/fern/profile.vim
- autoload/fern/scheme/file/provider.vim
- plugin/fern.vim
To investigate why fern.vim is slow in Windows
> Add profiler

- .github/workflows/linux_neovim.yml
- .github/workflows/linux_vim.yml
- .github/workflows/mac_neovim.yml
- .github/workflows/reviewdog.yml
- .github/workflows/windows_neovim.yml
- .github/workflows/windows_vim.yml
- README.md
.github/workflows are copied from https://github.com/prabirshrestha/vim-lsp
README badges are copied from https://github.com/mattn/vim-lsp-settings
Close #20
> Add Github Actions

- autoload/fern/scheme/file/provider.vim
Reverts lambdalisue/fern.vim#32
I may break.
> Revert "Use readdir"

- README.md
- autoload/fern/lib/buffer.vim
- autoload/fern/mapping/node.vim
https://vim-jp.slack.com/archives/CLKR04BEF/p1580371972234700
> Add edit-or-xxxxx for user who don't use 'hidden'

- autoload/fern/internal/spinner.vim
topline and botline are possibly upside down
> Fix spinner

- autoload/fern/internal/spinner.vim
> Sort by numbers

- README.md
Hi, thanks for the plugin. :)
I've opened this PR just to make clear how to select a node.
> Add information about how to select a node

- autoload/fern/mapping/open.vim
- autoload/fern/scheme/file/mapping/terminal.vim
For #46
Execute `open:side` or whatever. Note that `open:edit` open files on same window.
> Support open multiple nodes

- autoload/fern/internal/mapping.vim
- autoload/fern/mapping/filter.vim
- autoload/fern/mapping/node.vim
- autoload/fern/scheme/dict/mapping.vim
- autoload/fern/scheme/dict/provider.vim
- autoload/fern/scheme/dict/tree.vim
- autoload/fern/scheme/file/mapping.vim
- autoload/fern/scheme/file/shutil.vim
> Free from Prompt.ask

- autoload/fern/command/fern.vim
- autoload/fern/scheme/file/fri.vim
> Fix behavior to show root directory in Windows

- autoload/fern/internal/args.vim
- autoload/fern/scheme/file/mapping.vim
- autoload/fern/scheme/file/mapping/grep.vim
Hit `G` to grep contents under the cursor expanded directory (or parent directory of the cursor file/collapsed directory)
> Add 'grep' action on 'file' scheme

- plugin/fern.vim
> Load content after session load

- doc/fern.txt
> Add docs about mapping/glossary

- autoload/fern/scheme/file/mapping.vim
- doc/fern.txt
> Add "new-path" action

- autoload/fern/internal/action.vim
- autoload/fern/mapping/open.vim
- doc/fern.txt
> Action open or expand

- autoload/fern/scheme/file/bufutil.vim
- autoload/fern/scheme/file/mapping.vim
- autoload/fern/scheme/file/mapping/rename.vim
- test/behavior/buffer-rename.vimspec
1. Rename corresponding bufname after move/rename action
2. Remove corresponding (unmodified) buffer after trash/remove action
> Apply buffer modification after move/rename/trash/remove action

- autoload/fern/mapping/node.vim
- doc/fern.txt
Add `reload:all` and `reload:cursor` action and make `reload` action to an alias of `reload:all` action.
Close #156
> Add reload:all/reload:cursor action and reload links to reload:all

- autoload/fern.vim
- autoload/fern/internal/core.vim
- autoload/fern/logger.vim
- autoload/fern/scheme/file/util.vim
- autoload/vital/_fern/Async/Promise/Process.vim
- doc/fern.txt
- plugin/fern.vim
> Refactoring

- autoload/fern/internal/viewer.vim
- doc/fern-develop.txt
> Document refactoring

- autoload/fern/internal/drawer.vim
#173 
The error is look like not important.
So I hid the error.
> hide :new error (fix #173)

- test/.themisrc
- test/behavior/buffer-rename.vimspec
- test/behavior/test.vimspec
- test/fern/fri.vimspec
- test/util/autoload/test.vim
- test/util/test/test.vimspec
CI passed even the themis report failure on Neovim
> Fix CI silently fails on Neovim

- autoload/fern/helper/async.vim
- doc/fern-develop.txt
- test/fern/helper.vimspec
To enable https://github.com/lambdalisue/fern-mapping-mark-children.vim to close #184
> Add "get_child_nodes" on helper.async

- autoload/fern/internal/replacer.vim
> Renamer should be opened without 'noautocmd'

- autoload/fern/scheme/file/mapping/cd.vim
> Select window prior to 'lcd' action

- autoload/fern/fri.vim
- autoload/fern/helper/async.vim
- autoload/fern/internal/core.vim
- autoload/fern/internal/node.vim
- autoload/fern/internal/rename_solver.vim
- autoload/fern/internal/replacer.vim
- autoload/fern/internal/viewer.vim
- autoload/fern/renderer/default.vim
- autoload/fern/scheme/dict/mapping/rename.vim
- autoload/fern/scheme/file/mapping.vim
- autoload/fern/scheme/file/mapping/rename.vim
- autoload/fern/scheme/file/mapping/system.vim
- autoload/fern/scheme/file/provider.vim
- autoload/fern/scheme/file/util.vim
- autoload/vital/_fern/App/Action.vim
- autoload/vital/_fern/App/WindowSelector.vim
- autoload/vital/_fern/Async/Promise.vim
- autoload/vital/fern.vital
- doc/fern-develop.txt
- test/behavior/Fern.vimspec
- test/behavior/special-characters.vimspec
- test/fern/comparator/default.vimspec
- test/fern/internal/node.vimspec
- test/fern/internal/rename_solver.vimspec
- test/fern/internal/window.vimspec
Close #202
ref:
https://github.com/vim-jp/vital.vim/pull/755
https://github.com/lambdalisue/vital-Whisky/commit/295f8dd2d5e8d8ba1f1d907bdd66d5cacbe90ca4
> Add l: prefix to function local variables of funcref

- autoload/fern.vim
- autoload/fern/internal/drawer.vim
- doc/fern.txt
Close https://github.com/lambdalisue/fern.vim/issues/203
> Restore window focus when fern drawer window has closed

- autoload/fern/internal/drawer.vim
- test/behavior/drawer-auto-quit.vimspec
> Fix behavior on 'bdelete' command

- autoload/fern/mapping/open.vim
The bufname has already expanded absolute buffer name.
Close #225
> Do NOT expand bufname

- autoload/fern/internal/command/fern.vim
- autoload/fern/internal/viewer.vim
- autoload/fern/logger.vim
- autoload/fern/scheme/file/mapping/grep.vim
- autoload/fern/util.vim
> Fix expand() issue of completeslash on Windows

- autoload/fern/internal/command/fern.vim
> Check if reveal is empty or not first

- autoload/fern/internal/command/fern.vim
- autoload/fern/internal/command/reveal.vim
- autoload/fern/internal/viewer.vim
> Allow absolute paths on FernReveal command as well

- autoload/fern.vim
- autoload/fern/scheme/file/mapping.vim
- doc/fern.txt
Hi, Thank you for the great work.
I want to prevent to synchronize file remove operations so I create an option for it.
> Add `g:fern#disable_auto_buffer_delete` and `g:fern#disable_auto_buffer_rename`

- autoload/fern/internal/drawer.vim
> Force 'keepalt' on drawer style

- autoload/fern/scheme/file/mapping/terminal.vim
> Fix 'terminal' action from drawer

- autoload/fern.vim
- autoload/fern/internal/viewer.vim
- doc/fern.txt
> Add g:fern#disable_viewer_spinner to disable spinner

- autoload/fern/internal/drawer/auto_restore_focus.vim
> Check tabpage prior to restore focus

- autoload/fern/scheme/file/provider.vim
https://vim-jp.slack.com/archives/CLKR04BEF/p1604292119404600
> Fix listing issue junction in Windows

- autoload/fern/scheme/file/mapping.vim
Sorry. I was overlooked `s:map_remove` on my previous PR (#248)
> Fix auto_buffer_delete for s:map_remove

- autoload/fern/renderer/default.vim
> Add prefix on syntax match when smart_cursor is stick

- autoload/fern/fri.vim
- autoload/vital/_fern/System/Filepath.vim
- autoload/vital/_fern/System/Job/Neovim.vim
- autoload/vital/_fern/System/Job/Vim.vim
- autoload/vital/fern.vital
- test/fern/fri.vimspec
Fix FRI parse for `ssh://localhost/`
> Fix FRI parse

- autoload/fern/internal/command/do.vim
- autoload/fern/internal/command/fern.vim
- autoload/fern/internal/drawer.vim
> Do NOT use \< \> while these are affected by iskeyword

- autoload/vital/_fern/Async/File.vim
- autoload/vital/fern.vital
> Upgrade Vital modules to fix trash issue

- autoload/fern/internal/buffer.vim
> Use more user friendly name to open a new buffer

- autoload/fern/comparator/default.vim
- autoload/fern/internal/node.vim
- autoload/fern/util.vim
- doc/fern-develop.txt
- test/fern/internal/node.vimspec
> Ignore and remove expanded directory on 'reload' action if the directory has removed outside of fern

- autoload/fern/logger.vim
- doc/fern-develop.txt
> Add fern#logger#tap() for development

- .github/workflows/neovim.yml
- .github/workflows/vim.yml
- README.md
- autoload/fern/helper.vim
- autoload/fern/internal/drawer/auto_restore_focus.vim
- autoload/fern/internal/drawer/smart_quit.vim
- autoload/fern/internal/spinner.vim
- autoload/fern/internal/viewer.vim
- autoload/fern/internal/viewer/auto_duplication.vim
- plugin/fern.vim
I'd love to drop Vim 8.1 but there are several small fixes I can apply thus I tried.
Rel. #303
> Try to support old Vim

- autoload/fern/internal/viewer.vim
> Add 'foldmethod=manual' on fern buffer

- doc/fern.txt
> Remove unnecessary leading `\` from example

- autoload/fern/internal/drawer/auto_resize.vim
> Restore width on BufEnter as well

- autoload/fern/scheme/file/shutil.vim
> Return more detail on failure of `trash` action

- autoload/fern/scheme/file/complete.vim
> Use `'.'` instead of `''` in `fnamemodify`

- doc/fern.txt
Fixes the grammar and makes it easier to understand.
> Update documentation wording

- autoload/vital/_fern/Async/File.vim
- autoload/vital/fern.vim
- autoload/vital/fern.vital
> Update `Async.File` to fix `move` and `copy` in Neovim on Windows

- autoload/fern/scheme/file/provider.vim
- autoload/fern/scheme/file/util.vim
> Fix duplicated backslashes in `_path` on Windows

- autoload/fern/helper/sync.vim
- autoload/fern/internal/viewer.vim
- doc/fern-develop.txt
- plugin/fern.vim
> Properly restore fern on a different tab through session

- autoload/fern.vim
- autoload/fern/internal/command/fern.vim
- autoload/fern/internal/viewer/auto_duplication.vim
- doc/fern.txt
Create an universal fern tree for each left and right drawer
> Create universal fern tree

- autoload/fern.vim
- autoload/fern/internal/drawer.vim
- autoload/fern/internal/drawer/auto_restore_winfixwidth.vim
- doc/fern.txt
> Restore `winfixwidth` automatically

- doc/fern.txt
- plugin/fern.vim
> Disable fern with `shellslash` option

- autoload/fern/internal/drawer/auto_restore_focus.vim
- autoload/vital/_fern/App/Action.vim
- autoload/vital/_fern/App/WindowLocator.vim
- autoload/vital/fern.vital
> Fix invalid behavior when popup window is shown on Neovim

- autoload/fern/internal/drawer/auto_resize.vim
> Do NOT save winwidth on some situation to fix #432

- autoload/vital/_fern/App/WindowSelector.vim
- autoload/vital/fern.vital
> Fix: errors sometimes occur in window selection.

- README.md
Reference: https://github.com/lambdalisue/fern.vim/issues/120#issuecomment-1251890425.
> fix: Clarify wording about #120 in README

- autoload/fern/internal/viewer/auto_duplication.vim
> fix: Do NOT count popup windows on auto duplication (#474)

- autoload/fern/internal/node.vim
> Remove children cache on collapse
