autoload/fila/action.vim

Error occurred in fila-action-hidden-toggle
```
function <SNR>191_action_call_safe[4]..<SNR>183_call[4]..<SNR>190_hidden_toggle[4]..<SNR>181_redraw の処理中にエラーが検出されました:
行   10:
Cursor position outside buffer
```
Move cursor before fila-action-hidden-unset

Fix hidden_unset error

---

autoload/fila.vim
autoload/fila/node.vim
autoload/fila/node/helper.vim
autoload/fila/scheme/file.vim
autoload/fila/viewer.vim
autoload/fila/viewer/drawer.vim
plugin/fila/file.vim
test/fila/node.vimspec

This PR
- Remove invalid calls when "enter" action is called or drawer is opened
- Properly initialize the buffer on "enter/leave" actions
- Add unique suffix to make the buffer always fresh.
- Fix buffer synchronous issue
- Fix #12 
- Add `-reveal={path}` option to reveal a specified path
Open a fila buffer of the current working directory (e.g. `fila.vim`) with the current buffer 
(e.g. `fila.vim/autoload/fila/node/comparator/default.vim`) revealed.
```
:Fila . -reveal=%
```
Or with drawer style
```
:Fila . -drawer -reveal=%
```
When you use `:Fila . -reveal=%` in your mapping, you would noticed that the mapping does not work on a fresh new buffer.
Workaround is using `<C-r>=expand('%')<CR>` instead so that the `%` is not passed to the command.
```
nnoremap <silent> …
```

Add -reveal={path} option and fix behavior of drawer

---

autoload/fern/helper.vim
autoload/fern/internal/node.vim
test/fern/internal/node.vimspec

https://vim-jp.slack.com/archives/CLKR04BEF/p1580379370295400?thread_ts=1580377078.287400&cid=CLKR04BEF
As above, current `reveal` is not consisntent.

Fix `reveal` action

---

.github/workflows/linux_neovim.yml
.github/workflows/linux_vim.yml
.github/workflows/mac_neovim.yml
.github/workflows/reviewdog.yml
.github/workflows/windows_neovim.yml
.github/workflows/windows_vim.yml

actions/checkout@v2にアップグレード
こちらの方が実行時間が短くなります。
https://github.com/actions/checkout#whats-new

upgrade acitons/checkout v1 -> v2

---

autoload/vital/_fern/Async/Later.vim
autoload/vital/_fern/Async/Promise.vim
autoload/vital/fern.vital

Based on https://github.com/vim-jp/vital.vim/pull/716 so the PR must be merged to get this in.
The PR above improve performance especially on Windows.
```
fern#internal#viewer:init [enter] 
| fern#helper:helper.async.expand_node [enter] 
| | fern#internal#node#expand [enter] 
| | | fern#internal#node#children [enter] 
| | | | fern#scheme#file#provider:provider_get_children [enter] 
| | | | | fern#scheme#file#provider:children_vim_readdir [enter] 
| | | | | fern#scheme#file#provider:children_vim_readdir [leave] 0.002073 [0.002073]
| | | | fern#scheme#file#provider:provider_get_children [leave] 0.016929 [0.016929]
| | | fern#internal#node#children [leave] 0.019054 [0.019054]
| | | fern#internal#node#expand [children] 0.019879 [0.019879]
| | | fern#internal#node#expand [sort] 0.005746 …
```

Massive performance improvement on Windows

---

.github/workflows/neovim.yml
.github/workflows/vim.yml
autoload/fern/hook.vim
autoload/fern/internal/command/fern.vim
autoload/fern/internal/viewer.vim
doc/fern-develop.txt
doc/fern.txt
test/behavior/buffer-list.vimspec
test/fern/helper.vimspec
test/fern/hook.vimspec

Fern works asynchronously but sometimes that makes things complicated. A new `-wait` option waits until the fern buffer becomes ready.
For example
```
:Fern . | echomsg line('$')
```
Above *always* reports `1` whatever the actual content while the fern buffer has not ready yet when `line('$')` has called.
To report the correct value, use `-wait` like
```
:Fern . -wait | echomsg line('$')
```
Then the continuous command will be called AFTER the fern buffer becomes ready.

Add -wait option to wait fern buffer

---

autoload/fern/internal/bufname.vim
autoload/fern/internal/command/fern.vim
autoload/fern/internal/filepath.vim
autoload/fern/internal/path.vim
autoload/fern/internal/window.vim
autoload/fern/mapping/filter.vim
autoload/fern/mapping/node.vim
autoload/fern/mapping/tree.vim
autoload/fern/scheme/dict/provider.vim
autoload/fern/scheme/file/complete.vim
autoload/fern/scheme/file/fri.vim
autoload/fern/scheme/file/mapping.vim
autoload/fern/scheme/file/mapping/clipboard.vim
autoload/fern/scheme/file/provider.vim
autoload/fern/scheme/file/util.vim
autoload/vital/_fern/Async/CancellationToken.vim
autoload/vital/_fern/Async/CancellationTokenSource.vim
autoload/vital/_fern/Config.vim
autoload/vital/_fern/Data/List/Chunker.vim
autoload/vital/_fern/System/Job.vim
test/behavior/alternate-file.vimspec
test/behavior/jumplist.vimspec
test/fern/internal/bufname.vimspec
test/fern/internal/filepath.vimspec
test/fern/internal/path.vimspec

Close #70 
- Improve path handling by a new path module
- Support drives in Windows
- A parent node of `'C:\'` is `''` and it points drive root
- Users have to use `file:///` scheme to specify a drive root like `:Fern file:///`

Improve path

---

autoload/fern/helper/async.vim
autoload/fern/internal/buffer.vim
autoload/fern/internal/viewer.vim
plugin/fern.vim

Fixed #84. The status is **NOT** stored as a buffer name while
- Those status does NOT belongs to buffer/window, it belongs to `fern` instance which is isolated from buffer/window internally, thus technically it's bit difficult to store the value as a buffer name
- It would make people confused especially if `include/exclude` is applied to *a new fresh buffer* because of its buffer name, thus it should NOT stored as a buffer name to keep UX quality

Keep hidden/include/exclude after enter/leave

---

autoload/fern/internal/window.vim

Close #91
It seems the following code raise E474: Invalid argument sometime in Vim
execute printf("silent! cunmap \<buffer> \<Char-%d>", nr)
But the following
silent! execute printf("cunmap \<buffer> \<Char-%d>", nr)
Thus use former version to fix #91

Fix open:select action on Vim

---

autoload/fern/helper/async.vim
autoload/fern/scheme/dict/mapping.vim
autoload/fern/scheme/dict/mapping/clipboard.vim
autoload/fern/scheme/dict/mapping/rename.vim
autoload/fern/scheme/file/mapping.vim
autoload/fern/scheme/file/mapping/clipboard.vim
autoload/fern/scheme/file/mapping/rename.vim
doc/fern-develop.txt

Close #103
Note that it's nearly impossible to correctly reload expanded nodes thus collapse these instead.

Collapse nodes prior to modify (copy/move/remove/trash/rename)

---

autoload/fern/scheme/file/mapping/cd.vim

- Add cd:root/lcd:root/tcd:root action to perform cd/lcd/tcd on root node
- Add cd:cursor/lcd:cursor/tcd:cursor action to perform cd/lcd/tcd on cursor node
- Alias cd/lcd/tcd to cd:cursor/lcd:cursor/tcd:cursor for backward compatibility
This PR partially fix #107 while current `cd/lcd/tcd` action always refer the cursor node.

Improve cd/lcd/tcd action in file scheme

---

autoload/fern/internal/command/do.vim
autoload/fern/internal/command/fern.vim
autoload/fern/internal/command/focus.vim
doc/fern.txt
plugin/fern.vim

To solve #94, `:FernDo` command has added.
For example, if users want to close fern drawer after `open`action then
```vim
nmap <buffer><silent> <Plug>(fern-my-open-and-close)
\ <Plug>(fern-action-open)
\ :<C-u>FernDo close -drawer -stay<CR>
```
In favor of `:FernDo`, the `:FernFocus` command become deprecated. Use `:FernDo :` instead.

Add :FernDo command and deprecate :FernFocus command

---

autoload/fern/mapping.vim
autoload/fern/mapping/wait.vim
doc/fern.txt

While #108 is too complicated for users, this is a different approach.
User can wait an asynchronous action by `<Plug>(fern-wait)` thus users can define mappings like
```vim
nmap <buffer> <Plug>(my-fern-enter-or-tcd)
\ <Plug>(fern-action-enter)
\ <Plug>(fern-wait)
\ <Plug>(fern-action-tcd:root)
```

Add <Plug>(fern-wait) to synchronously wait asynchronous action

---

autoload/fern/helper/async.vim
autoload/fern/internal/core.vim
autoload/fern/internal/viewer.vim
autoload/vital/_fern/Async/CancellationTokenSource.vim
autoload/vital/_fern/Async/Promise/Process.vim
autoload/vital/fern.vim
autoload/vital/fern.vital
doc/fern-develop.txt
plugin/fern.vim
test/fern/internal/core.vimspec

To develop https://github.com/lambdalisue/fern-plugin-git.vim for #122

Prepare for fern-plugin-xxxxx

---

autoload/fern.vim
autoload/fern/helper/async.vim
autoload/fern/internal/mark.vim
autoload/fern/internal/node.vim
autoload/fern/internal/spinner.vim
autoload/fern/internal/viewer.vim
autoload/fern/mapping/mark.vim
autoload/fern/mapping/open.vim
autoload/fern/renderer/default.vim
autoload/fern/scheme/dict/mapping/clipboard.vim
autoload/fern/scheme/file/mapping/clipboard.vim
autoload/fern/scheme/file/mapping/terminal.vim
doc/fern-develop.txt
doc/fern.txt
test/behavior/Fern.vimspec
test/fern/helper.vimspec
test/fern/renderer/default.vimspec

*fern with git status integration (under development)*
To support 3rd party integration like Git status, the following changes had applied
- Use signs to indicate marked nodes
- Add "badge" attribute on nodes to indicate the node status
- Misc.
**This PR will break the existing 3rd party renderer**. See https://github.com/lambdalisue/fern-renderer-nerdfont.vim/pull/2 if you'd like to support a new fern on your custom renderer.

Use sign instead to display marks and add "badge" support for 3rd parties

---

autoload/fern/internal/scheme.vim
autoload/fern/scheme/dict/mapping.vim
autoload/fern/scheme/file/mapping.vim
doc/fern-develop.txt

SSIA
e.g. https://github.com/lambdalisue/fern-mapping-git.vim

Support 3rd party scheme mappings and document mappings on developer docs

---

autoload/fern/internal/window.vim
doc/fern.txt

Support custom highlight in window select

---

autoload/fern/helper/sync.vim
autoload/fern/internal/viewer.vim

Close #136
**Note that** fern does NOT re-apply `-reveal` on the existing buffer but fern **restore** the previous cursor position.
The above behavior had broken in Vim if users did not move cursor thus this PR correct the behavior in Vim.
1. `:e README.md`
2. `:Fern . -drawer -toggle -reveal=%` - The cursor is on `README.md`
3. `:q`
4. `:Fern . -drawer -toggle -reveal=%` - The cursor is on `README.md` again
5. Move cursor on `doc` and expand - The cursor is on `fern-develop.txt`
6. `:q`
7. `:Fern . -drawer -toggle -reveal=%` - The cursor is on `fern-develop.txt` rather than `README.md` even `-reveal` points `README.md`

Fix ambigious cursor position on Vim

---

plugin/fern.vim

If Vim version is earlier than 8.1, this plugin will not load.

add check v:version

---

autoload/fern/helper.vim
autoload/fern/internal/spinner.vim

After splitting Fern window, this plugin uses the cursor position in first window whose buffer is target Fern buffer (`bufwinid(bufnr)`).
If focusing the window whose buffer is target Fern buffer, use a cursor position of that window.

Use current window position if the buffer of that window is same as target.

---

autoload/fern.vim
autoload/fern/internal/viewer.vim
doc/fern.txt

Now fern automatically duplicate the buffer when user hit `split` or `vsplit` so that the content of each window can be different.
Users can disable this feature by `g:fern#disable_viewer_auto_duplication`

Automatically duplicate the buffer on split/vsplit for convinience

---

autoload/fern/internal/rename_solver.vim
autoload/fern/internal/replacer.vim
autoload/fern/scheme/dict/mapping/rename.vim
autoload/fern/scheme/dict/tree.vim
autoload/fern/scheme/file/mapping/rename.vim
autoload/vital/_fern/Async/Promise.vim
autoload/vital/fern.vital
test/fern/internal/rename_solver.vimspec

This PR fix numerous rename issue on `rename` action of `file` and `dict` scheme.
```
foo -> a
bar -> b
```
```
foo   -> bar
foo/a -> bar/b
foo/c -> bar/c
```
```
foo     -> a/foo
foo/a   -> a
```
```
foo -> bar
bar -> foo
```
```
a   -> b
a/b -> b/c
a/c -> b/b
```
```
foo   -> bar
foo/a -> bar
```
```
foo   -> bar
foo/a -> bar/b
```
Above renames on the follwoing tree should be avoided **before** actual renames.
```
foo
|- a
|- b
```
```
foo   -> a/foo
foo/a -> a
```
Above fails if `foo/a` is file.

Support complex renaming via 'rename' action of 'file' or 'dict' scheme

---

autoload/fern/internal/command/fern.vim
autoload/fern/internal/complete.vim
autoload/fern/internal/viewer.vim
autoload/fern/mapping/node.vim
autoload/fern/scheme/file/complete.vim
doc/fern.txt

Fix #114 
Users can reveal a path on the current fern viewer with `FernReveal {reveal} [-wait]` command.
Use `FernDo` command to execute `FernReveal` from different buffer.
Fix #146

Improve "reveal" related features

---

autoload/fern.vim
autoload/fern/internal/cursor.vim
autoload/fern/internal/viewer.vim
doc/fern.txt

Now fern automatically hide cursor on viewer. The feature can be disabled by `g:fern#disable_viewer_hide_cursor = 1`

Automatically hide cursor on fern viewer

---

autoload/fern/fri.vim
test/fern/fri.vimspec

Related #145
There was a bug in the decoding of strings that contained multiple percent encodings.
BTW. encoding has no bug, but why don't use `substitute(..., 'g')` in encode?
It's faster and implements to simply.

Fix FRI parse

---

autoload/fern/renderer/default.vim
test/behavior/Fern.vimspec
test/behavior/special-characters.vimspec
test/fern/renderer/default.vimspec

```vim
let g:fern#renderer#default#leading = "│"
let g:fern#renderer#default#root_symbol = "┬─ "
let g:fern#renderer#default#leaf_symbol = "├─ "
let g:fern#renderer#default#collapsed_symbol = "├─ "
let g:fern#renderer#default#expanded_symbol = "├┬ "
```

Fix highlight issue on the default renderer

---

autoload/fern/action.vim
autoload/fern/mapping.vim
autoload/fern/mapping/filter.vim
autoload/fern/mapping/mark.vim
autoload/fern/mapping/open.vim
autoload/vital/_fern/App/Action.vim
doc/fern.txt

| Previous        | Current         |
| --------------- | --------------- |
| `hidden-set`    | `hidden:set`    |
| `hidden-unset`  | `hidden:unset`  |
| `hidden-toggle` | `hidden:toggle` |
| | `hidden` |
| `mark-clear`    | `mark:clear`    |
| `mark-set`      | `mark:set`      |
| `mark-unset`    | `mark:unset`    |
| `mark-toggle`   | `mark:toggle`   |
| | `mark` |
All previous mappings/actions become deprecated. Users should use the new one.

Rename hidden/mark mappings/actions (previous one become deprecated)

---

autoload/fern/scheme/file.vim
autoload/fern/scheme/file/provider.vim
doc/fern.txt

Close #178 
Add the following to enable the option
```vim
let g:fern#scheme#file#show_absolute_path_on_root_label = 1
```
The option **only affect the "file" scheme**.

Add an option to show absolute path of "file" scheme root node

---

autoload/fern/internal/viewer.vim
autoload/fern/mapping.vim
autoload/fern/mapping/drawer.vim
autoload/fern/mapping/filter.vim
autoload/fern/mapping/mark.vim
autoload/fern/mapping/node.vim
autoload/fern/mapping/open.vim
autoload/fern/mapping/tree.vim
autoload/fern/scheme/dict/mapping.vim
autoload/fern/scheme/dict/mapping/clipboard.vim
autoload/fern/scheme/dict/mapping/rename.vim
autoload/fern/scheme/file/mapping.vim
autoload/fern/scheme/file/mapping/clipboard.vim
autoload/fern/scheme/file/mapping/rename.vim
autoload/fern/scheme/file/mapping/system.vim
doc/fern-develop.txt
doc/fern.txt
test/behavior/drawer-auto-quit.vimspec

Close #212
This PR removes some default mappings
```vim
nmap <buffer><nowait> <C-j> <Plug>(fern-action-mark)j
nmap <buffer><nowait> <C-k> k<Plug>(fern-action-mark)
nmap <buffer><nowait> <C-m> <Return>
nmap <buffer><nowait> <C-h> <Backspace>
```

Use hasmapto to define built-in mappings

---

autoload/fern/mapping/node.vim
doc/fern.txt

To solve #210 
1. Add `expand:stay` action which does NOT move cursor (what @noscript suggested)
2. Add `expand:in` action which move cursor when the node has children (what @winkee01 suggested)
3. Alias `expand` action to `expand:in` for backward compatibility

Add expand:stay/expand:in actions

---

autoload/fern/mapping.vim
autoload/fern/mapping/yank.vim
autoload/fern/scheme/file/mapping.vim
autoload/fern/scheme/file/mapping/yank.vim
doc/fern.txt

Now users can yank the path of the node (or bufname of the node in non file:// scheme) by `y`.

Add 'yank' actions

---

autoload/fern/internal/viewer.vim
autoload/fern/mapping.vim
autoload/fern/mapping/drawer.vim
autoload/fern/mapping/filter.vim
autoload/fern/mapping/mark.vim
autoload/fern/mapping/node.vim
autoload/fern/mapping/open.vim
autoload/fern/mapping/tree.vim
autoload/fern/mapping/yank.vim
autoload/fern/scheme/dict/mapping.vim
autoload/fern/scheme/dict/mapping/clipboard.vim
autoload/fern/scheme/dict/mapping/rename.vim
autoload/fern/scheme/file/mapping.vim
autoload/fern/scheme/file/mapping/clipboard.vim
autoload/fern/scheme/file/mapping/rename.vim
autoload/fern/scheme/file/mapping/system.vim
doc/fern-develop.txt
doc/fern.txt

#218 introduce #221 and I now think the original want (#212) does not fit on fern's mapping system thus revert it.

Revert "Use hasmapto to define built-in mappings" which cause mapping overwrite issue

---

autoload/fern/internal/command/reveal.vim
autoload/fern/internal/complete.vim
test/fern/internal/complete.vimspec

- Remove deprecated command completion.
- Add completion for `:FernDo` and `:FernReveal`.
- Fix completion pattern matching.
- Add tests.

fix command option completion

---

autoload/fern/internal/complete.vim
autoload/fern/scheme/file/complete.vim
test/fern/internal/complete.vimspec

- Fix completion of `-reveal=`
- Add tests
Before this PR, completion of `-reveal=` with filepath was always relative to the current directory.
Fix it to a relative path from the base path, same way as URL completion.

fix command url and filepath completion

---

autoload/fern/internal/spinner.vim
doc/fern.txt

I think it would be useful if users could customize the color of spinner, so I added `FernSpinner` highlight group for it.
If you prefer a different name, please let me know and I'll change it.

Add highlight group used for spinner

---

autoload/fern/internal/buffer.vim

In case buffer is not modified `opener` should be `'edit'`.
From logs without this:
```
[fern] DEBUG: fern#internal#buffer#open cmdline edit/tabedit .gitattributes
```

Fix 'open:edit-or-*' action

---

autoload/fern/internal/drawer/auto_resize.vim
doc/fern.txt

Disable auto-resize on flaoting window of Neovim

---

autoload/fern/mapping/node.vim
doc/fern.txt

Could easily be a plugin but it felt like it might belong here.
The action is style as `focus:x` for any future actions that might also set the focus.
A default mapping of `p` is added.

Add new focus:parent action

---

autoload/fern/internal/drawer/auto_resize.vim
autoload/fern/mapping/drawer.vim
doc/fern.txt

To help usage explained in #309 
- :boom: Behavior changed. Fern restore the previous drawer width on the `BufEnter` autocmd to fix #309 
- It's more natural to restore the previous width rather than the original one
- Users can use `<Plug>(fern-action-zoom:reset)` action to mimic previous behavior if they desire
- :boom: Behavior changed. The `zoom` action opens a prompt to ask a desired width ratio or respects `v:count`
- For example, users can use `8z` to make the drawer width 80% of the Vim window
- Users can map `<Plug>(fern-action-zoom:half)` or `<Plug>(fern-action-zoom:full)` to `z` to get back the previous mapping
- :sparkles: Feature added: The `zoom:reset` action is added to easily get back to the original width of the drawer
---
In the video below, I use the following mappings …

Change behavior of "auto resize" and improve "zoom" related actions

---

autoload/fern/internal/cursor.vim

Fix cursor hide in GUI vim

---

autoload/fern/mapping.vim
autoload/fern/mapping/diff.vim
autoload/fern/scheme/file/mapping.vim
autoload/fern/scheme/file/mapping/ex.vim
doc/fern.txt

Users can use `diff` action to compare buffer contents of multiple nodes.
https://user-images.githubusercontent.com/546312/124349629-0b867e00-dc2b-11eb-91ac-67a1d7741433.mp4
Users can use `ex` action to execute arbitrary Ex command on selected nodes.
https://user-images.githubusercontent.com/546312/124349659-52747380-dc2b-11eb-8df3-601aa8a30820.mp4

Add `diff` and `ex` actions

---

autoload/fern/mapping.vim
autoload/fern/mapping/filter.vim
autoload/fern/mapping/node.vim
autoload/fern/scheme/file/mapping.vim
autoload/fern/scheme/file/mapping/ex.vim
autoload/fern/scheme/file/mapping/grep.vim
doc/fern.txt

With this PR, users can provide mappings with default value like:
```vim
nmap <buffer> <Plug>(fern-action-dirdiff) <Plug>(fern-action-ex=)DirDiff<CR>
```
Above add `dirdiff` action which execute [`:DirDiff`](https://github.com/will133/vim-dirdiff) command on marked file scheme nodes.
https://user-images.githubusercontent.com/546312/124349770-d75f8d00-dc2b-11eb-9d77-8caf49d1762d.mp4

Add `=` action variants to several actions for providing default value

---

autoload/fern/helper/sync.vim
autoload/fern/internal/command/do.vim
autoload/fern/internal/command/fern.vim
autoload/fern/internal/drawer.vim
autoload/fern/internal/drawer/auto_resize.vim
autoload/fern/mapping/open.vim
autoload/fern/smart.vim
doc/fern-develop.txt
doc/fern.txt

Add `-right` option to place drawer on right side

---

autoload/fern/internal/viewer/hide_cursor.vim

The `cursorlineopt` was introduced at patch 8.1.2019 but at that time, the
default value was `both` and `,` is not allowed in the value.
After patch 8.1.2029, `,` is allowed and the default value became `number,line`.
Neovim nightly (2021/08/01) raise E474 because https://github.com/neovim/neovim/pull/15161
only introduce patch 8.1.2019.
Thanks @yuki-yano

Fix `E474: Invalid argument: cursorlineopt=number,line` in Neovim nightly

---

autoload/fern/internal/viewer.vim
syntax/fern.vim

Use `syntax/fern.vim` instead to define syntax/highlight

---

autoload/fern.vim
autoload/fern/internal/drawer.vim
autoload/fern/internal/drawer/hover_popup.vim
doc/fern.txt

In cases where the node name extends beyond the width of the drawer
window (often the case with long file names or a deeply nested tree),
show a popup to help the user view the full node name.
Closes #395 
These changes have been well tested in my environment (`VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)`), but I haven't tested these changes against newer versions of vim. I also haven't tested these changes in Neovim. I gather that popup functionality in Neovim is in flux at the moment. I added a guard to check if `popup_create` exists, which may be implemented by a plugin like `plenary.nvim`, but I'm not sure if that will work properly in neovim or not. If someone could help me test that in Neovim, I would greatly appreciate!
It was a bit tricky making sure that …

Show popup when node name extends beyond drawer width

---

autoload/fern/scheme/file/util.vim

Previous fern.vim can't list file entries containing even one self-referenced symlink because a `find` command invoked in the background emits an error such as `Too many levels of symbolic links` by the `-follow` option. The option tries to dereference symlinks in listing files. But we only need to dereference symlinks on the command line, but not dereference symlinks in listing files. So we should use the `-H` option, which doesn't dereference symlinks except on the command line, instead of the `-follow` option.
This problem happens on Linux, but not macOS. The `find` command installed in macOS by default doesn't emit errors in the situation above.
Fixes #384.

Fix failures to list self-referenced symlink

---

autoload/fern.vim
autoload/fern/internal/drawer/hover_popup.vim
doc/fern.txt

This PR aims to improve the hover popup feature.
1. Support neovim
2. Support directory coloring
3. Support debounce
https://user-images.githubusercontent.com/629908/158536287-71f17e84-4a40-4e4d-859c-c9a1f440ce64.mp4
https://user-images.githubusercontent.com/629908/158536957-ca6a9113-5837-448a-be5e-56f04468dc8e.mp4

Improve hover popup behavior

---

autoload/fern/internal/drawer.vim
doc/fern.txt

Enable hover_popup feature only on left sided drawer

---

autoload/fern/mapping/node.vim
autoload/fern/mapping/open.vim

NeoVim introduced a breaking change that breaks indirect mapping of
`<Return>` and `<Backspace>` to a command via `<C-m>` and `<C-h>`.
(https://github.com/neovim/neovim/issues/14090#issuecomment-1113090354)
Mapping them directly fixes the problem and is clearer.

Map <Return> and <Backspace> directly to <Plug> commands

---

plugin/fern.vim

The actual option variable is `fern_disable_startup_warnings` but the "s" is missing in the startup warning message.

Fix typo in startup warning message

---

autoload/fern/internal/drawer/smart_quit.vim
test/behavior/drawer-smart-quit.vimspec

Fix 'E242' when smart-quit feature on Neovim 0.7.1

---

autoload/fern/internal/drawer.vim
autoload/fern/internal/drawer/hover_popup.vim
doc/fern.txt

When navigating through nodes in a drawer window, node names that extend beyond the width of the fern window are shown in a popup to display the full name to the user.
A regression introduced in 10dd4bb (Improve hover popup behavior, 2022-03-16) prevented the popup from being positioned correctly in drawer windows positioned on the right side. As a result, the hover popup behavior was disabled for right hand drawers in ab237a1 (Merge pull request #419 from lambdalisue/fix-popup-right, 2022-04-15).
This revision reintroduces this functionality, ensuring that the popup windows are positioned correctly in all cases.
Fixes https://github.com/lambdalisue/fern.vim/issues/418
I haven't tested this in neovim. I don't use neovim myself, so any assistance would be hugely appreciated!
Popup text …

Correct hover popup position on right side drawer

---

autoload/fern/renderer/default.vim
doc/fern-develop.txt

The syntax highlighting in the default renderer doesn't match the root node, meaning that any default or custom highlighting does not apply correctly. This has been corrected in this revision.

renderer: fix syntax highlight for root symbol

---

autoload/fern/internal/drawer/hover_popup.vim

:bug: Fix "E118: Too many arguments for function: getcurpos"

---

autoload/fern/internal/drawer.vim

If the `Fern -drawer` command is executed again when Drawer is already open, WinLeave and WinEnter commands will not fire due to noautocmd.
This could be fixed and cause problems, but I'd like to try it in and see!

Remove noautocmd when open exists drawer

---

autoload/fern/renderer/default.vim
doc/fern.txt

Prior to this revision, the leading symbols of a branch or leaf node inherited the highlight group from the branch or leaf symbol, which doesn't look appealing when they are assigned different highlight groups.
This revision introduces a new syntax group FernLeaderSymbol which may be highlighted separately from the node symbols. Documentation is updated accordingly.
The screenshot below demonstrates a before and after.
Fixes https://github.com/lambdalisue/fern.vim/issues/461

introduce separate syntax group for leader symbol

---

autoload/fern.vim
autoload/fern/internal/buffer.vim
autoload/fern/internal/drawer/hover_popup.vim
doc/fern-develop.txt
doc/fern.txt
test/fern/internal/buffer.vimspec

Introduce the ability to render text with attached text properties. Renderers may now return list of dictionaries where each line of text can include text properties for additional text styling capabilities. This change is backwards compatible with existing renderers; they will continue to work as before.
The semantics of this feature was inspired by popup_create(), which can accept a list of dictionaries with a 'text' and 'props' key.
This feature enhances the capabilities of custom renderers. In particular, it's possible to implement renderers that render content with dynamically-defined style. The screenshot below shows a simple custom renderer that renders vim files in green, config files in grey and others in orange.
Here's a renderer I built using these features: …

feat: add support for rendering text with props

---

autoload/fern/internal/node.vim
test/fern/internal/node.vimspec

The function should be immutable but it mutate `nodes` in current implementation. This PR makes the function immutable.
I think this would drastically simplify the code of #480

Fix immutability of `fern#internal#node#expand()` function

---

autoload/fern/helper/async.vim
autoload/fern/internal/node.vim
autoload/fern/mapping/node.vim
doc/fern-develop.txt
doc/fern.txt
test/fern/internal/node.vimspec

Original PR is #480 
I rewrote `fern#internal#node#expand_tree` because of #482

Add action to open a subtree recursively (v2)
